spring:
    application:
        name: flightsight-back
    security:
        user:
            name: seb
            password: seb123
    datasource:
        url: jdbc:postgresql://host.docker.internal:5432/db_flightsight
        username: flightsight_user
        password: flightsight_password
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

