spring:
    application:
        name: flightsight-back
    datasource:
        url: jdbc:postgresql://localhost:5432/db_flightsight
        username: flightsight_user
        password: flightsight_password
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /flightsight-api-docs
